### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by joshmedeski** [garrettkrohn/treekanga#9]
As a user, I want to use a wildcard to match multiple paths, so that I can use a single rule to match multiple paths.

```yml
 example:
    zoxideFolders:
      - packages/*
```
